### ISSUE TITLE
Área Copiável 

### ISSUE THREAD

**Issue by Keith1Richard** [CECALC/xl-calculos-judiciais#1]
Considerando a necessidade de copiar um intervalo com várias células (área), a fim de que os períodos de contribuição sejam transportados da planilha de TC para a de RMI, solicito a implementação desse recurso no suplemento.

**Comment by cmlima** [comment]
@Keith1Richard e @efujit ,
Já é possível obter esse resultado, bastando expandir a área do intervalo nomeado o quanto for necessário. Por exemplo, se o intervalo contiver quatro colunas e 100 linhas, essa área inteira é copiada para a memória e depois colada na planilha de destino.
