### ISSUE TITLE
Contagem: Data Final

### ISSUE THREAD

**Issue by giovani84** [CECALC/xl-calculos-judiciais#10]
Se na aba TCDiscriminado a data final for igual a data inicial, a data final na aba Demonstrativo será igual ao dia anterior do vínculo seguinte.
![print 2](https://user-images.githubusercontent.com/108829001/177616053-0307ab9f-5cd7-4593-be3d-f916253287e0.jpg)
![print 1](https://user-images.githubusercontent.com/108829001/177616061-77c51047-fab7-4cfc-ab6d-dca04fbb2f79.jpg)

**Comment by efujit** [comment]
Transferido para repositório CalculoTC
https://github.com/CECALC/CalculoTC/issues/1
