### ISSUE TITLE
Contagem: Salários

### ISSUE THREAD

**Issue by giovani84** [CECALC/xl-calculos-judiciais#13]
Na aba salários há uma diferença de 11 anos e 1 mês entre os valores importados do Cnis para a planilha, o que afeta a análise das contribuições efetuadas com o salário mínimo.
![print 1](https://user-images.githubusercontent.com/108829001/177625805-297dc830-c0a0-4797-8d31-4e7208b7921d.jpg)
![print 2](https://user-images.githubusercontent.com/108829001/177625821-a4404261-b57c-4644-bcbd-2436f5f149a1.jpg)
![print 3](https://user-images.githubusercontent.com/108829001/177625859-871cce69-c923-4710-ac10-36028fd13ae0.jpg)
![print 4](https://user-images.githubusercontent.com/108829001/177625879-6f5dc609-40e7-41fd-94fb-3e236cd13fad.jpg)

**Comment by efujit** [comment]
Transferido para repositório CalculoTC
https://github.com/CECALC/CalculoTC/issues/2
